### ISSUE TITLE
NPP plugin fails to save formatting options

### ISSUE THREAD

**Issue by PacoAbel** [TaoK/PoorMansTSqlFormatter#189]
I just updated the PMSF plugin in NPP (to version 1.6.10.1279).  When saving the formatting options I get the following error message:

- ![image](https://user-images.githubusercontent.com/34173256/33504736-2fce5214-d6ae-11e7-835d-70abc3307584.png)

When clicking the reset button I get a different message window, with the same error:

-![image](https://user-images.githubusercontent.com/34173256/33504782-782a17f0-d6ae-11e7-9d71-e11ba740e595.png)

Text is : 
>See the end of this message for details on invoking 
>just-in-time (JIT) debugging instead of this dialog box.
>
>************** Exception Text **************
>System.IO.FileNotFoundException: Could not load file or assembly 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
>File name: 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
>   at System.Configuration.TypeUtil.GetTypeWithReflectionPermission(IInternalConfigHost host, String typeString, Boolean throwOnError)
>   at System.Configuration.MgmtConfigurationRecord.CreateSectionGroupFactory(FactoryRecord factoryRecord)
>   at System.Configuration.MgmtConfigurationRecord.EnsureSectionGroupFactory(FactoryRecord factoryRecord)
>   at System.Configuration.MgmtConfigurationRecord.GetSectionGroup(String configKey)
>   at System.Configuration.Configuration.GetSectionGroup(String sectionGroupName)
>   at System.Configuration.ClientSettingsStore.DeclareSection(Configuration config, String sectionName)
>   at System.Configuration.ClientSettingsStore.GetConfigSection(Configuration config, String sectionName, Boolean declare)
>   at System.Configuration.ClientSettingsStore.WriteSettings(String sectionName, Boolean isRoaming, IDictionary newSettings)
>   at System.Configuration.LocalFileSettingsProvider.SetPropertyValues(SettingsContext context, SettingsPropertyValueCollection values)
>   at System.Configuration.SettingsBase.SaveCore()
>   at System.Configuration.SettingsBase.Save()
>   at System.Configuration.ApplicationSettingsBase.Save()
>   at PoorMansTSqlFormatterPluginShared.SettingsForm.btn_Reset_Click(Object sender, EventArgs e)
>   at System.Windows.Forms.Control.OnClick(EventArgs e)
>   at System.Windows.Forms.Button.OnClick(EventArgs e)
>   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
>   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
>   at System.Windows.Forms.Button.WndProc(Message& m)
>   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
>   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>
>WRN: Assembly binding logging is turned OFF.
>To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
>Note: There is some performance penalty associated with assembly bind failure logging.
>To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
>
>
>
>************** Loaded Assemblies **************
>mscorlib
>    Assembly Version: 2.0.0.0
>    Win32 Version: 2.0.50727.8762 (QFE.050727-8700)
>    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
>----------------------------------------
>PoorMansTSqlFormatterNppPlugin
>    Assembly Version: 1.6.10.1279
>    Win32 Version: 1.6.10.1279
>    CodeBase: file:///C:/Program%20Files%20(x86)/Notepad++/plugins/PoorMansTSqlFormatterNppPlugin.dll
>----------------------------------------
>PoorMansTSqlFormatterLib
>    Assembly Version: 1.6.10.1278
>    Win32 Version: 1.6.10.1278
>    CodeBase: file:///C:/Program%20Files%20(x86)/Notepad++/plugins/PoorMansTSqlFormatterNppPlugin/PoorMansTSqlFormatterLib.dll
>----------------------------------------
>System
>    Assembly Version: 2.0.0.0
>    Win32 Version: 2.0.50727.8770 (QFE.050727-8700)
>    CodeBase: file:///C:/windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
>----------------------------------------
>PoorMansTSqlFormatterPluginShared
>    Assembly Version: 1.6.10.1279
>    Win32 Version: 1.6.10.1279
>    CodeBase: file:///C:/Program%20Files%20(x86)/Notepad++/plugins/PoorMansTSqlFormatterNppPlugin/PoorMansTSqlFormatterPluginShared.dll
>----------------------------------------
>System.Windows.Forms
>    Assembly Version: 2.0.0.0
>    Win32 Version: 2.0.50727.5491 (Win7SP1GDR.050727-5400)
>    CodeBase: file:///C:/windows/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
>----------------------------------------
>System.Drawing
>    Assembly Version: 2.0.0.0
>    Win32 Version: 2.0.50727.5495 (Win7SP1GDR.050727-5400)
>    CodeBase: file:///C:/windows/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
>----------------------------------------
>System.Configuration
>    Assembly Version: 2.0.0.0
>    Win32 Version: 2.0.50727.5483 (Win7SP1GDR.050727-5400)
>    CodeBase: file:///C:/windows/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
>----------------------------------------
>System.Xml
>    Assembly Version: 2.0.0.0
>    Win32 Version: 2.0.50727.5494 (Win7SP1GDR.050727-5400)
>    CodeBase: file:///C:/windows/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll
>----------------------------------------
>LinqBridge
>    Assembly Version: 1.2.0.0
>    Win32 Version: 1.2.13016.2208
>    CodeBase: file:///C:/Program%20Files%20(x86)/Notepad++/plugins/PoorMansTSqlFormatterNppPlugin/LinqBridge.DLL
>----------------------------------------
>
>************** JIT Debugging **************
>To enable just-in-time (JIT) debugging, the .config file for this
>application or computer (machine.config) must have the
>jitDebugging value set in the system.windows.forms section.
>The application must also be compiled with debugging
>enabled.
>
>For example:
>
><configuration>
>    <system.windows.forms jitDebugging="true" />
></configuration>
>
>When JIT debugging is enabled, any unhandled exception
>will be sent to the JIT debugger registered on the computer
>rather than be handled by this dialog box.
>
Has anyone encountered this before?  Is there any fix or workaround?

Thanks in advance for the help.

Regards
Pacoabel

**Comment by PacoAbel** [comment]
Solved it by removing and reinstalling notepad++.....

Thanks....
