### ISSUE TITLE
This extension cannot be installed because the following references are missing

### ISSUE THREAD

**Issue by spottedmahn** [TaoK/PoorMansTSqlFormatter#225]
>7/17/2019 4:36:58 PM - Beginning to install extension to Microsoft Visual Studio Enterprise 2019...
7/17/2019 4:37:01 PM - Install Error : Microsoft.VisualStudio.ExtensionManager.MissingReferencesException: This extension cannot be installed because the following references are missing:
-Microsoft.VisualStudio.Component.CoreEditor (Microsoft.VisualStudio.Component.CoreEditor)
-Microsoft.VisualStudio.Component.Web (Microsoft.VisualStudio.Component.Web)
   at Microsoft.VisualStudio.ExtensionManager.EngineUtilities.EnsureNoMissingReferences(IEnumerable`1 missingRefs)
   at Microsoft.VisualStudio.ExtensionManager.PackageInstaller.PrepareEngineInstall(IDependencyGraph dGraph, IDependencyComparisonSeed seed, Component vsixComponent, Boolean isProductComponent, Int32& totalInstallationSteps)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineInstall(InstallableExtensionImpl extension, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion, IInstalledExtension& newExtension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)

![image](https://user-images.githubusercontent.com/14079228/61410066-968cd300-a8b1-11e9-92bb-aed47f5d8ca8.png)

**Comment by TaoK** [comment]
I just released a new version, and "it works for me" :) - can you confirm whether it works in **your** VS 2019 environment please?

https://twitter.com/PoorSQL/status/1155471888145141761

**Comment by spottedmahn** [comment]
![image](https://user-images.githubusercontent.com/14079228/62052043-b80b8a00-b1e2-11e9-8af1-9542e6a4073b.png)

thanks!

**Comment by spottedmahn** [comment]
How do I use it though?  I don't see anything the right click context menu.  I don't see anything in the extensions menu.

And I don't see [anything in the marketplace](https://marketplace.visualstudio.com/items?itemName=TaoKlerks.PoorMansT-SqlFormatterSSMSVSExtension) showing how to invoke it.

🤔

**Comment by spottedmahn** [comment]
Opened a separate issue: https://github.com/TaoK/PoorMansTSqlFormatter/issues/228
